@startuml

title __DATA_AGENTS's Class Diagram__\n

  namespace ru.omegapps.wisherapp {
    namespace data_agents {
      class ru.omegapps.wisherapp.data_agents.FireBaseDataAgent {
          {static} ~ currentUser : FirebaseUser
          {static} - PUBLIC_WBLOCK_KEY : String
          {static} - WBLOCK_KEY : String
          {static} - WISH_KEY : String
          {static} - mAuth : FirebaseAuth
          {static} - privateUserWishBlocks : ArrayList<WishBlock>
          {static} - publicWishBlockRef : DatabaseReference
          {static} - publicWishBlocks : ArrayList<WishBlock>
          {static} - userWishBlocks : ArrayList<WishBlock>
          {static} - userWishes : ArrayList<Wish>
          {static} - wishBlockRef : DatabaseReference
          {static} - wishRef : DatabaseReference
          {static} + getBlocksByTags()
          {static} + init()
          {static} + logout()
          {static} + pushWish()
          {static} + updatePublicWishBlock()
          {static} - getAllNeededBlocks()
      }
    }
  }
  

  namespace ru.omegapps.wisherapp {
    namespace data_agents {
      class ru.omegapps.wisherapp.data_agents.LocalDataAgent {
          {static} + blocks : ArrayList<WishBlock>
          {static} + wishes : ArrayList<Wish>
          + getBlocks()
          + getBlocksByTags()
          + getWishes()
          + pushBlock()
          + pushWish()
      }
    }
  }
  

  ru.omegapps.wisherapp.data_agents.LocalDataAgent .up.|> ru.omegapps.wisherapp.interfaces.DataAgent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
